name: Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: true
        run: |
          echo "Start"
          npm init -y
          npm i cloudflared
          npm list
          npx cloudflared bin
          npx cloudflared -v

      - run: |
          cat /home/runner/.npm/_logs/*.log
