name: Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Start"
          npm init -y
          npm i cloudflared
          npm list
          npx cloudflared bin
          npx cloudflared -v
